name: CI/CD for Dockerized Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  dockerbuild: #we can specifu any names to our jobs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 #The actions/checkout@v3 step is used to clone (download) your GitHub repository into the runner (i.e., the virtual machine where your workflow runs).
    - name: Build The Docker Image
      run: docker build . --file DockerFile --tag workflow-test:$(date +%s)

  build-and-test:                      # ✏️ Job name (you define this)
    runs-on: ubuntu-latest            # ✅ GitHub-hosted runner (you pick a valid one, like 'ubuntu-latest')

    steps:                            # ✅ Required keyword to define all steps
    - name: Checkout code           # ✏️ Human-readable step name
      uses: actions/checkout@v4     # ✅ Official GitHub Action to clone your repository

    - name: Set up Python           # ✏️ Descriptive step name
      uses: actions/setup-python@v4  # ✅ GitHub Action to install and configure Python
      with:                         # ✅ Keyword to pass configuration inputs
        python-version: '3.9'       # ✏️ Python version (you choose this version)

    - name: Install dependencies    # ✏️ Step name
      run: |                        # ✅ Shell command block
        python -m pip install --upgrade pip     # ✏️ Custom command to upgrade pip
        pip install flask                       # ✏️ You choose which packages to install
        pip install pytest                      # ✏️ Installing test framework

    - name: Run tests               # ✏️ Step name
      run: |                        # ✅ Shell command block
        pytest                      # ✏️ Test command (you define what to run)

  build-and-publish:                         # ✏️ Job name (you define this)
    needs: build-and-test                    # ✏️ Depends on another job (must match your other job's name)
    runs-on: ubuntu-latest                   # ✅ GitHub-hosted runner (must be a valid option)

    steps:                                   # ✅ Required keyword to define all steps
    - name: Checkout code                  # ✏️ Step name (for readability)
      uses: actions/checkout@v4            # ✅ Official GitHub Action to clone your repo

    - name: Set up Docker Buildx           # ✏️ Descriptive step name
      uses: docker/setup-buildx-action@v2  # ✅ Marketplace action to enable advanced Docker builds

    - name: Login to DockerHub             # ✏️ Your step name
      uses: docker/login-action@v2         # ✅ DockerHub login action
      with:                                # ✅ Used to pass inputs
        username: ${{ secrets.DOCKER_USERNAME }}  # ✅ Uses GitHub secret (you define the name in Secrets)
        password: ${{ secrets.DOCKER_PASSWORD }}  # ✅ Also from Secrets

    - name: Build and push Docker image          # ✏️ Step name
      id: docker_build                           # ✏️ Custom ID for referencing outputs later
      uses: docker/build-push-action@v4          # ✅ Official build & push action
      with:                                      # ✅ Required for action inputs
        context: .                               # ✏️ Build context (here, current directory)
        file: ./Dockerfile                       # ✏️ Path to your Dockerfile
        push: true                               # ✅ Pushes image to registry (DockerHub)
        tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest  # ✏️ Custom image tag using your username

    - name: Image digest                         # ✏️ Descriptive step name
      run: echo ${{ steps.docker_build.outputs.digest }}  # ✅ Access output from previous step by ID
